apiVersion: v1
kind: Service
metadata:
  name: sql-server
  namespace: smart-stock-analyzer
spec:
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: sql-server
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  namespace: smart-stock-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-secrets
              key: sa-password
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        volumeMounts:
        - name: sql-data
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-data
        emptyDir: {}
