apiVersion: v1
kind: ServiceAccount
metadata:
  name: portfolio-service
  namespace: smart-stock-analyzer

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: analysis-service
  namespace: smart-stock-analyzer

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portfolio-service-role
  namespace: smart-stock-analyzer
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: analysis-service-role
  namespace: smart-stock-analyzer
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portfolio-service-binding
  namespace: smart-stock-analyzer
subjects:
- kind: ServiceAccount
  name: portfolio-service
  namespace: smart-stock-analyzer
roleRef:
  kind: Role
  name: portfolio-service-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analysis-service-binding
  namespace: smart-stock-analyzer
subjects:
- kind: ServiceAccount
  name: analysis-service
  namespace: smart-stock-analyzer
roleRef:
  kind: Role
  name: analysis-service-role
  apiGroup: rbac.authorization.k8s.io
